### ISSUE TITLE
Images not registering when creating new species

### ISSUE THREAD

**Issue by jimbo4273** [Loreinator/Shuffle-Move#220]
I have been trying to make new species for Pokémon such as Meloetta and all of the unreleased Winking Pokémon. Whenever I go to set the data, the icon I used doesn't show.
[bugReport_20161109_102614_CST.zip](https://github.com/Loreinator/Shuffle-Move/files/581330/bugReport_20161109_102614_CST.zip)

**Comment by Manitary** [comment]
I think I found the problem, Meloetta wasn't associated to any icon in the folder because of a typo. It should be fixed with #219

**Comment by jimbo4273** [comment]
Thanks for the Meloetta fix, yet, it still doesn't work when doing it for the unreleased Winking Pokemon. Do I need to put those sprites in ShuffleMove's sprite folder?

**Comment by Loreinator** [comment]
Meloetta is now in the live version, please let me know if there are any further problems with this species.
